version: "2"
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/webapp:/app
    ports:
      - 8080:80
    image: my-apache2
  nginx:
    build: ./nginx
    ports: 
        - 1337:80
    depends_on: 
        - app

  app:
    build:
      context: ./backend
    expose:
      - 8000
    volumes:
      - ./backend/app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&  
             gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=789456123
