const PROTOCOL = 'http';
const STATIC_SERVER_HOST = 'localhost';
const STATIC_SERVER_PORT = '80';
const API_SERVER_HOST = 'localhost';
const API_SERVER_PORT = '80';

const STATIC_SERVER_URL = PROTOCOL + '://' + STATIC_SERVER_HOST + ':' + STATIC_SERVER_PORT;
const API_SERVER_URL = PROTOCOL + '://' + API_SERVER_HOST + ':' + API_SERVER_PORT;
